{
  config,
  lib,
  pkgs,
  inputs,
  userName,
  stateVersion,
  globals,
  ...
}: {

  # ===========================================================================
  # Localization & Time Zones
  # ===========================================================================
  time.timeZone = globals.timeZone;

  # ===========================================================================
  # User Administration & Shell Configurations
  # ===========================================================================
  users = {
    # Disable user additions at runtime. All users must be configured declaratively.
    mutableUsers = false;

    users.${userName} = {
      isNormalUser = true;
      description = "Primary User";
      
      # Reference password hash securely generated by SOPS-nix.
      hashedPasswordFile = config.sops.secrets.user_password_filip.path;
      
      # User group privileges (wheel: sudo, video/audio: hardware device access).
      extraGroups = ["wheel" "video" "audio"];
      
      shell = pkgs.fish;
      
      createHome = true;
      homeMode = "700";
    };
  };

  programs.fish.enable = true;

  # ===========================================================================
  # System Packages & Global Environments
  # ===========================================================================
  environment = {
    variables = {
      EDITOR = "nvim";
      VISUAL = "nvim";
    };

    systemPackages = with pkgs; [
      just      # Command executor and workflow orchestrator.
      nushell   # Modern, structured terminal shell environment.
    ];
  };

  # ===========================================================================
  # Nix Package Manager & Store Engine Settings
  # ===========================================================================
  nix = {
    settings = {
      # Allow primary user and root to perform administrative builds.
      trusted-users = ["root" userName];
      allowed-users = ["@wheel" userName];

      # Auto-deduplicate identical store files to save storage space.
      auto-optimise-store = true;

      # Enable remote builders to request substitutes from configured caches.
      builders-use-substitutes = true;

      # CPU core limits for builds (0 instructs Nix to use all available cores).
      cores = 0;
      max-jobs = "auto";

      # Public binary cache substitutions for faster, pre-built package downloads.
      substituters = [
        "https://nix-community.cachix.org"
      ];
      trusted-public-keys = [
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];

      experimental-features = ["nix-command" "flakes"];

      warn-dirty = false;
    };

    # Disable automatic garbage collection, leaving store cleanup tasks to Justfile control.
    gc.automatic = false;

    # Dynamic registry mapping to pin active inputs, ensuring super-fast nix-shell evals.
    registry = lib.mapAttrs (_: value: {flake = value;}) inputs;
    nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;
  };

  # ===========================================================================
  # Low-level Kernel & Performance Enhancements
  # ===========================================================================
  # Force systemd manager runtime watchdogs to handle hard lockups elegantly.
  systemd.settings.Manager = {
    RuntimeWatchdogSec = "30s";
    RebootWatchdogSec = "10m";
  };

  zramSwap.enable = true;
}
